### PR TITLE
Add _impl suffix, remove export roxygen2 tag

### PR DESCRIPTION
**Pull request by krlmlr**
For https://github.com/igraph/rigraph/pull/712.

### CODE REVIEW

**Comment by krlmlr** [comment]
@ntamas: How does tagging happen in this repository? I can work against the branch for now.

**Comment by ntamas** [comment]
> How does tagging happen in this repository?

I use `tbump` to make sure that all version numbers are updated in all files at once. So, with a clean repo, I can run `tbump 0.11.1` to bump the version number to 0.11.1, run all tests (if there are any), run any pre-commit hooks (if there are any), then tag the commit and push the tag.

Looking into `tbump.toml`, it seems like in this particular repo I only run `pre-commit run --all-files` as there are no tests to run. The pre-commit hooks are defined in `.pre-commit-config.yaml`, which involves syntax checks, end-of-line fixes, trimming whitespace, running a formatter and a linter.

Shall I tag the current state as 0.11.1 or 0.12.0, or will you just point your side at the exact commit instead?

**Comment by krlmlr** [comment]
For now, I'm pointing to my branch from igraph, I'll be careful to not delete or change it until done. I don't have a preference regarding the version number.

**Comment by ntamas** [comment]
Tagged the current head with 0.12.0, FYI.

**Pull request merged**
