### PR TITLE
add `IGRAPH_R_CHECK`

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]

**Review by ntamas — APPROVED** [review]

**Comment by krlmlr** [comment]
Thanks. Each new version needs a tag. Should we automate that?

**Comment by ntamas** [comment]
No, I can tag manually if you want to (I'll just set up `tbump` for the repo), I just wasn't sure whether you want to point to tags when declaring stimulus as a dependency, or you are okay with pointing to a commit hash.

**Comment by ntamas** [comment]
Tagged head as 0.13.0, FYI.

**Comment by krlmlr** [comment]
Pointing to commits would be completely fine too.

**Pull request merged**
