### PR TITLE
igraph 0.10

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
Let me know when this can be merged - it's still marked as a draft.

**Comment by Antonov548** [comment]
> Let me know when this can be merged - it's still marked as a draft.

Thanks for review. I think it will make sense to merge when igraph in R repository will be fully compilable, there is still RR part not ready, maybe will be required changes to generate r interface.

**Comment by szhorvat** [comment]
Is this branch up to date and is this what you're using with https://github.com/igraph/rigraph/pull/840, @Antonov548 ?

**Comment by Antonov548** [comment]
> 

Yes, it's what I use for igraph 0.10.

**Review by krlmlr — APPROVED** [review]
Thanks, looks good! Can we please merge to simplify workflows?

**Comment by ntamas** [comment]
Pls fix the typo of `teamplate` to `template` in `r.py`, mark it as ready to merge and then I'll merge.

**Comment by ntamas** [comment]
Merged, tagged as 0.17.0

**Pull request merged**
